기본 플레이리스트 관련 UseCase 작성
f-lab-edu/play-your-color pull request #13
Opened 2022-06-27 04:54 UTC by Jeong-heon2

## PR 타입
- [x] 기능 추가 
- [ ] 버그 수정
- [x] 의존성, 빌드 관련 코드 업데이트 
- [ ] 기타 사소한 수정 

## 개요 
#12 

## 변경 사항 
- 기본 플레이리스트 관련 Repository 추가 
- 기본 플레이리스트에서 음악 `삭제` UseCase 추가 
- 기본 플레이리스트에서 음악 `순서 변경` UseCase 추가 
- 기본 플레이리스트에 음악 `추가` UseCase 추가 
- 기본 플레이리스트 `전체 리스트 요청` UseCase 추가 
- 기본 플레이리스트 `색상별 리스트 요청` UseCase 추가 
- 음악 삭제 및 순서 변경 후 리스트에서 순서 변경 정보를 구하는 유틸 함수 `getChangedOrderList` 추가 
- `getChangedOrderList` 테스트 코드 작성 

## 코드 리뷰시 참고 사항 
- 플레이리스트에서 음악을 삭제할 때, 현재 재생중인 노래를 삭제 시키면 그에 대한 처리도 해야 하는데,  현재 재생중인 노래에 대한 정보를 어떻게 저장할지 정해지지 않아 이 부분은 로직에서 빠져있습니다. 추후에 추가되어야 합니다. 
- 음악 삭제 및 순서 변경 후, 리스트에서 순서 변경이 일어나야 하는 요소들의 정보를 구하는 함수를 유틸 함수로 따로 뺐습니다. 
예를 들면 0 번 삭제 ->  1, 2, 3 ... 번  순서를 앞으로 한 칸씩 당겨야 함 
리턴 타입이 `List<Pair<Int, Int>>` 인데, Pair<from, to> :  from 에서 to 로 순서를 바꿔야 한다는 의미입니다. 
## 스크린샷

2022-06-28 12:44 UTC, hyun17171771 requested changes

2022-06-28 12:44 UTC, hyun17171771 commented on domain/src/main/java/pyc/domain/repository/PrimaryPlaylistRepository.kt
> +    fun updateAudioOrder(changedOrderList: List<Pair<Int, Int>>): Completable
updateAudioOrder 메서드 매개변수를 Pair(from, to) List로 하신 건 from 값을 조건으로 업데이트를 하기 위함인가요?

제 생각하기론 primaryPlayListId 값과 바뀐 order 값을 넘겨줘서 primaryPlayListId을 조건으로 order 값을 업데이트 시켜주는 게 더 간편할 거란 생각이 듭니다.

추가적으로 생각이 나서 말씀드리는 부분인데, 현재 PrimaryPlaylist dto에서 order 값을 unique = true로 설정해놓은 상태입니다.

-> 이 상황에서 예를 들어 1번 order인 곡과 2번 order인 곡의 순서를 맞바꾼다고 했을 때 업데이트 시 unique키 중복으로 인한 에러가 발생할 수 있을 거란 예상이 듭니다. 이 부분에 대해 논의가 필요할 듯 싶습니다

2022-06-28 12:44 UTC, hyun17171771 commented on domain/src/main/java/pyc/domain/common/PlaylistUtils.kt
> +fun getChangedOrderList(listSize: Int, deleteOrderList: List<Int>): List<Pair<Int, Int>> {
1. 매개변수명이 listSize이라 하면 삭제 전 size인지 삭제 후 size인지 불분명 합니다

2. 저는 리스트 변경(+순서 변경)에 따른 order 값 변경은 바뀐 list 인덱스 값으로 계산해서 넣으면 될 거라고 생각하는데 바뀐 순서를 계산하는 로직 함수를 만드신 다른 이유가 혹시 있으신 지 궁금합니다. 

list(곡1(order = 1),곡2(order = 2),곡3(order = 3),) -> list(곡1(순서 변동 없음), 곡3(order = 3 -> 현재 index+1 값으로 변경))

2022-07-04 10:34 UTC, Jeong-heon2 commented on domain/src/main/java/pyc/domain/common/PlaylistUtils.kt
> +fun getChangedOrderList(listSize: Int, deleteOrderList: List<Int>): List<Pair<Int, Int>> {
model 을 다시 정의하고 수정했습니다

2022-07-04 10:34 UTC, Jeong-heon2 commented on domain/src/main/java/pyc/domain/repository/PrimaryPlaylistRepository.kt
> +    fun updateAudioOrder(changedOrderList: List<Pair<Int, Int>>): Completable
[6c0892b](https://github.com/f-lab-edu/play-your-color/pull/13/commits/6c0892b46a9a2a99a618862e86f8e74549ae48be) 에서 반영했습니다

2022-07-04 10:37 UTC, merged